name: Run Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run Tests (API)
        run: pnpm run test:api
        env:
          URL: ${{ secrets.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CI: ${{ secrets.CI }}

      - name: Run Tests (UI)
        run: pnpm run test:ui
        env:
          URL: ${{ secrets.URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CI: ${{ secrets.CI }}

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: ./allure-report
          allure_history: ./allure-history

      - name: Publish on Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          retention-days: 1
          path: |
            ./playwright-report/
            ./test-results/
