name: Run Tests (Allure, Docker)
on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Build Docker Image
        run: |
          docker build -t playwright-tests .

      - name: Run Tests (API) inside Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/test-results:/app/test-results \
          -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          -w /app \
          -e URL=${{ secrets.URL }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e CI=${{ secrets.CI }} \
          playwright-tests \
          pnpm run test:api

      - name: Run Tests (UI) inside Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/test-results:/app/test-results \
          -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          -w /app \
          -e URL=${{ secrets.URL }} \
          -e PASSWORD=${{ secrets.PASSWORD }} \
          -e CI=${{ secrets.CI }} \
          playwright-tests \
          pnpm run test:ui

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          retention-days: 1
          path: |
            ./playwright-report/
            ./test-results/
            ./allure-results/